<?php
bolt_decrypt( __FILE__ , 'BiWRXQ'); return 0;
##!!!##BwdrXmpicG1eYGIdSmxhcmlicFlNQUpKTGtmcWxvZmtkWUVxcW1ZQGxrcW9saWlib3A4BwdycGIdPm1tWUVxcW1ZQGxrcW9saWlib3BZQGxrcW9saWlibzgHcnBiHUZpaXJqZmtecWJZRXFxbVlPYm5yYnBxOAcHYGlecHAdTUFKSkxrZnFsb2ZrZEBsa3FvbGlpYm8dYnVxYmthcB1AbGtxb2xpaWJvB3gHHR0dHQd6